# Generated by Django 3.2.5 on 2021-07-21 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrdersDetail',
        ),
    ]
