# Generated by Django 3.2.5 on 2021-07-21 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_delete_ordersdetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={},
        ),
    ]
