# Generated by Django 3.2.5 on 2021-07-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderstatus_produts'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='products',
            field=models.ManyToManyField(to='orders.Produts'),
        ),
    ]
