# Generated by Django 3.2.5 on 2021-07-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_orders_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('market_price', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Produts',
        ),
        migrations.AlterField(
            model_name='orders',
            name='products',
            field=models.ManyToManyField(to='orders.Products'),
        ),
    ]
